# ------------------------------------------------------------------------------------------

#  $$$$$$\                      $$\
# $$  __$$\                     $$ |
# $$ /  \__| $$$$$$\   $$$$$$\  $$$$$$$\   $$$$$$\  $$$$$$$\
# $$ |       \____$$\ $$  __$$\ $$  __$$\ $$  __$$\ $$  __$$\
# $$ |       $$$$$$$ |$$ |  \__|$$ |  $$ |$$ /  $$ |$$ |  $$ |
# $$ |  $$\ $$  __$$ |$$ |      $$ |  $$ |$$ |  $$ |$$ |  $$ |
# \$$$$$$  |\$$$$$$$ |$$ |      $$$$$$$  |\$$$$$$  |$$ |  $$ |
#  \______/  \_______|\__|      \_______/  \______/ \__|  \__|

# Carbon by orbyfied <https://github.com/orbyfied/carbon>, under the Apache License 2.0
# Root configuration file. Sorry for the big text lol it looks cool

# ------------------------------------------------------------------------------------------

# ======== CORE ========= */
