# Main Properties
name: Carbon
main: net.orbyfied.carbon.bootstrap.Carbon1182Bootstrap
version: '$${carbonProjectVersion}'

# For 1.18 (this platform)
api-version: 1.18

# We want it to load as early as possible.
load: STARTUP

# Dependencies
libraries:
  - "org.zeroturnaround:zt-zip:1.15"