# ------------------------------------------------------------------------------------------

#  $$$$$$\                      $$\
# $$  __$$\                     $$ |
# $$ /  \__| $$$$$$\   $$$$$$\  $$$$$$$\   $$$$$$\  $$$$$$$\
# $$ |       \____$$\ $$  __$$\ $$  __$$\ $$  __$$\ $$  __$$\
# $$ |       $$$$$$$ |$$ |  \__|$$ |  $$ |$$ /  $$ |$$ |  $$ |
# $$ |  $$\ $$  __$$ |$$ |      $$ |  $$ |$$ |  $$ |$$ |  $$ |
# \$$$$$$  |\$$$$$$$ |$$ |      $$$$$$$  |\$$$$$$  |$$ |  $$ |
#  \______/  \_______|\__|      \_______/  \______/ \__|  \__|

# Carbon by orbyfied <https://github.com/orbyfied/carbon>, under the Apache License 2.0
# Root configuration file. Sorry for the big text lol it looks cool
--config-version: 1

# ------------------------------------------------------------------------------------------

# ======== RESOURCES ======= */

# Resource pack building properties
resource-pack-builder:

  # The number of threads to use for building
  # Default = 8
  threads: 8

# Resource pack hosting properties
resource-pack-host:

  # The strategy to use for pack hosting
  # Default = HTTP
  strategy: http

  # The settings for the host
  settings:

    # ONLY FOR HTTP
    # The port to host it on
    port: 25566

    # ONLY FOR FILEBIN
    # The bin ID to host the file on.
    # Generate this at https://filebin.net
    bin: 0

# Configuration and properties for world
# data management, with things like chunk
# loading, data fixing, etc.
world-manager:

  # Asynchronous chunk loading configuration.
  async-chunk-loading:

    # The amount of threads to use
    # for asynchronous chunk loading.
    # NOTE: The server REQUIRES a restart for
    #   any changes to this property to take effect
    #   Simply reloading the configuration won't work.
    threads: 8

# Minecraft Vanilla content definitions
minecraft-definitions:

  # Item definitions
  # TODO: implement
  items:

    stone: { "tags" : ["stone"] }
    iron_ingot: { "tags" : ["ingot.iron"] }
    gold_ingot: { "tags" : ["ingot.gold"] }
    diamond: { "tags" : ["gem.diamond", "diamond"] }
